import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import {Providers} from "./providers";
import  "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";

const kodeMono = localFont({
  src: [
    {
      path: './fonts/Kode/KodeMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Kode/KodeMono-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Kode/KodeMono-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-kode-mono'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${kodeMono.className} ${kodeMono.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
